### PR TITLE
Add support for slot variables

### PR DESCRIPTION
**Pull request by msukmanowsky**
Adds support for:

- slot_xpath
- slot_url
- slot_x
- slot_y

### CODE REVIEW

**Comment by msukmanowsky** [comment]
Before merging this, I'm generally concerned that adding new fields will break BigQuery. If a new field is added to a Redshift schema, it's generally harmless because Redshift's `COPY` command looks for fields that are present in the current table (thus, it ignores new fields it encounters that aren't present in the schema).

In BigQuery however, we use the [insertAll](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll) command and specify `ignoreUnknownValues=False` meaning that, from my read, if you try inserting a JSON record with fields not present in the schema, it'll fail.

I'm wondering if we should just change `ignoreUnknownValues=true` for our BQ streaming inserts as part of this change? Allows users to add support for new fields in their schema over time instead of forcing an immediate break in their load command.

Thoughts @amontalenti?

**Comment by msukmanowsky** [comment]
@rachelannelise do you know the answer to this one?

**Comment by rachelannelise** [comment]
@msukmanowsky it looks like both a table configuration setting and an insert setting:
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables

externalDataConfiguration.ignoreUnknownValues:

Optional] Indicates if BigQuery should allow extra values that are not represented in the table schema. If true, the extra values are ignored. If false, records with extra columns are treated as bad records, and if there are too many bad records, an invalid error is returned in the job result. The default value is false. The sourceFormat property determines what BigQuery treats as an extra value: CSV: Trailing columns JSON: Named values that don't match any column names Google Cloud Bigtable: This setting is ignored. Google Cloud Datastore backups: This setting is ignored. Avro: This setting is ignored.

**Comment by rachelannelise** [comment]
closing - this is old and no longer relevant

**Pull request closed without merging**
