### PR TITLE
Validation function

### PR DESCRIPTION
**Pull request by aldraco**
Works on a python dict representation of a data pipeline event (i.e. json loads). Can raise an Error, or simply log it for testing.

### CODE REVIEW

**Comment by rachelannelise** [comment]
What about `available_when_true` instead of `available_with_field`? I think that reads logically and is intuitive

**Comment by aldraco** [comment]
@rachelannelise that would work, except for the `url_query` field, which is not a boolean, but rather a string.

**Comment by rachelannelise** [comment]
Should we make a url_query equivalent boolean field for consistency?

**Comment by aldraco** [comment]
We could add a different field, but then we are changing the schema/table definition, as well as muddying the meaning of each of those fields somewhat. It's also something we would need to add on our side w.r.t. processing events. I would prefer to avoid adding new fields, unless it adds value to the customer that we can't provide otherwise, since it necessitates both us and customers changing their processing patterns.

I think you're right that consistency is important, though. The naming convention should reflect some meaning and consistency that isn't otherwise there w.r.t field names and types.

**Comment by rachelannelise** [comment]
Good point - since it is a different type of field maybe it should be `available_when_not_null` and `available_when_true` since they should be treated as difference cases from an ETL consumption perspective.

**Pull request merged**
