### PR TITLE
schema.py: add new fields

### PR DESCRIPTION
**Pull request by conradlee**
Add recently-added fields to `schema.py`

### CODE REVIEW

**Comment by kbourgoin** [comment]
@conradlee I'm not really familiar enough with the project to know if this is a good idea or not. It looks fine to me, but @emmett9001 or @dan-blanchard should comment. I'd be interested to know so that I can answer this question in the future.

**Comment by dan-blanchard** [comment]
I've never actually messed with the schema aspect of things.  I would actually suggest @aldraco or @amontalenti, who worked on #7 as good reviewers.

**Comment by aldraco** [comment]
One thing to keep in mind is making sure that all possible values that could be passed for each of these fields will fit into the various SQL type-equivalents based on the "type" you specify in schema.py.

For example, if you have a timestamp, it won't fit as an INT, it needs to be a bigint. Etc. That's probably not an issue, given what those items are, but you never know.

Redshift is the only format here that uses the 'size' parameter given in the base schema definition, so it's worth trying to load some sample data into a Redshift table just to make sure it works. The default for Redshift is to truncate anything that's too long, e.g. 
https://github.com/Parsely/parsely_raw_data/blob/master/parsely_raw_data/redshift.py#L98

Bigquery doesn't seem to give a string length limit:
https://cloud.google.com/bigquery/data-types

**Comment by conradlee** [comment]
@msukmanowsky or @amontalenti  any thoughts on whether we should add these campaign related fields to our public data pipeline schema?  As far as I recall, these fields end up in our enriched events (they make their way into events via [url_utils](https://github.com/Parsely/parselyutils/blob/f793d36ccbebaecf9356875bf2c3637009d022aa/parselyutils/url_utils.py).

**Comment by msukmanowsky** [comment]
Hmm `campaign_id` is probably the only one worth adding since we have some custom logic for those. For other `utm_*` params, we add these [already](https://github.com/Parsely/engineering/blob/master/casterisk-realtime/casterisk/lib/data_pipeline/enrichments.py#L143-L159) to DPL, it just seems to not be reflected by this schema which I'd assume is just an oversight.

Fields we're already populating:

* `utm_campaign`: `?utm_campaign` found in (uncleaned) `url`
* `utm_medium`: `?utm_medium` found in (uncleaned) `url`
* `utm_source`: `?utm_source` found in (uncleaned) `url`
* `utm_term`: `?utm_term` found in (uncleaned) `url`
* `utm_content`: `?utm_content` found in (uncleaned) `url`
* `surl_utm_campaign`: `?utm_campaign` found in (uncleaned) `session['url']`
* `surl_utm_medium`: `?utm_medium` found in (uncleaned) `session['url']`
* `surl_utm_source`: `?utm_source`found in (uncleaned) `session['url']`
* `surl_utm_term`: `?utm_term` found in (uncleaned) `session['url']`
* `surl_utm_content`: `?utm_content` found in (uncleaned) `session['url']`

I'd propose adding these to the schema, plus two new ones to reflect the custom code in campaign IDs:

* `campaign_id`
* `surl_campaign_id`

**Pull request merged**
